# Generated by Django 4.0.6 on 2025-01-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('video_url', models.URLField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='clase.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentaciones', to='clase.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='materiales/')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='clase.clase')),
            ],
        ),
    ]
